### ISSUE TITLE
Problem : Installation request requires symfony/dependency-injection ^3.1 

### ISSUE THREAD

**Issue by opal-up** [SuperdeskWebPublisher/SWPMultiTenancyBundle#6]
Hi,
I'm trying to add **MultiTenacyBundle** to My Project based on Symfony4.
and I got this error : 

Problem 1
    - Installation request for swp/multi-tenancy-bundle ^1.4 -> satisfiable by swp/multi-tenancy-bundle[v1.4.0].
    - swp/multi-tenancy-bundle v1.4.0 requires symfony/dependency-injection ^3.1 -> no matching package found.

In my project composer.json, I have : 

"symfony/dependency-injection": "4.2.*"

Why it's obligatory to have 3.1 on **MultiTenacyBundle** ??

**Comment by takeit** [comment]
Hi @aziizoon we are currently working on SF4 integration. Here is the PR: https://github.com/superdesk/web-publisher/pull/643

I will continue with this in the upcoming days. PRs are welcome too :)

**Comment by HICHAMOSDEV** [comment]
Hi,

I have the same problem with symfony 4.

:(

**Comment by takeit** [comment]
Hi, please try version `^2.0` and not `^1.4`. 2.x is compatible with Symfony >=4.2.

**Comment by takeit** [comment]
fixed in https://github.com/superdesk/web-publisher/pull/774

**Comment by HICHAMOSDEV** [comment]
Hi,
Thank you it works but I have another error ( In SWPMultiTenancyExtension.php line 67:  You need to enable one of the peristence backends (phpcr or orm) )

do I have to add another parameter ?

![1](https://user-images.githubusercontent.com/49071331/56156852-5f5f0b00-5fbe-11e9-8140-3aa793d4ef2e.png)

**Comment by HICHAMOSDEV** [comment]
Hi,

Thanks, but after installation i have another problem with symfony 4.

i don't know why !!! 

![1](https://user-images.githubusercontent.com/49071331/56174434-c5658580-5ff2-11e9-9e21-5d156ec15623.png)

**Comment by takeit** [comment]
if you use it with PHPCR - the `phpcr` persistence backend is enabled in your config - you have to install `doctrine/phpcr-odm` additionally. Otherwise, enable `orm` persistence backend in the bundle config.

**Comment by HICHAMOSDEV** [comment]
Hi,

Thanks, but I think there is another problem 

I configured the phpcr and then I tried to install with "composer require swp/multi-tenancy-bundle "^2.0"

i have this error:

![1](https://user-images.githubusercontent.com/49071331/56320871-0a0d3000-615d-11e9-9181-ab9cff3c3547.png)

**Comment by HICHAMOSDEV** [comment]
I try with this version "^ 1.0" of ocramius / proxy-manager but it generates a conflict with doctrine / migrations v2.0.0

![2](https://user-images.githubusercontent.com/49071331/56321004-61ab9b80-615d-11e9-8574-5cc1c2a1026d.png)
